* =yaqubro.li= site source
Work in progress.

Features I intend to implement:

- Using an =org-roam= database as a headless CMS for next.js SSG
  - Only zettels with specific tags will be pushed to the website; zettel tags will also be used for classification of zettels on the website.
- Automatic uploading to neocities

** Licensing

Copyright (c) 2023, Jacob Walchuk

All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, and distribute copies of the Software, subject to the following conditions:

1. The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

2. Any redistribution of this Software, in any form, must include some form of attribution acknowledging the contribution of Jacob Walchuk. The method and format of this attribution are left to the discretion of the redistributor, provided it is in good faith and reasonably accessible to users of the redistributed Software.

3. Any modifications to the original Software must result in a significant visual alteration of the Software's interface and presentation ("look and feel"), to the extent that it does not bear a substantial resemblance to the original Software.

4. No person or entity may use the name of Jacob Walchuk or yaqubro.li to endorse or promote products derived from this Software without specific prior written permission from Jacob Walchuk.

THIS SOFTWARE IS PROVIDED BY JACOB WALCHUK "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL JACOB WALCHUK BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
